version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: padelo_api_app
    ports:
    - '8000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # anonymous volume
    command: npm run start:dev
    environment:
      - CHOKIDAR_USEPOLLING=true # untuk hot reload di Docker
      - WATCHPACK_POLLING=true

  db:
    image: postgres:17-alpine
    container_name: padelo_postgres_db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres_data:
